### ISSUE TITLE
cors issue

### ISSUE THREAD

**Issue by yovanoc** [hyperium/tonic#1636]
### Version

```
├── tonic v0.11.0
├── tonic-web v0.11.0
│   ├── tonic v0.11.0 (*)
└── tonic-build v0.11.0
```

### Platform

Darwin mbp-1.home 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:10 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6031 arm64

### Description

I tried this code:

```rust
  let server = HealthServer { addr };

  let svc = pb::health_server::HealthServer::with_interceptor(server, check_auth);

  let cors = CorsLayer::new()
            .allow_headers(Any)
            .allow_methods([Method::GET, Method::POST])
            .allow_origin(Any);

        let serve = Server::builder()
            .trace_fn(|_| tracing::info_span!("health_server"))
            .accept_http1(true)
            .layer(cors)
            .layer(GrpcWebLayer::new())
            .add_service(svc)
            .serve(addr);
```

I expected to see this happen: should build

Instead, this happened:
<img width="1645" alt="Screenshot 2024-02-20 at 13 27 22" src="https://github.com/hyperium/tonic/assets/7302317/f63f6cde-3409-4312-9a60-370e0376f0de">

**Comment by boan-anbo** [comment]
Same issue. Mine Grpc setup with cors was working fine before upgrading to `11.0` from `10.02`.

```rust
    Server::builder()
        .accept_http1(true)
        .layer(CorsLayer::new())
        .layer(GrpcWebLayer::new())
        .add_service(reflection_service)
        .serve(address)
        .await
     
```

My error:
```bash
error[E0277]: the trait bound `Cors<GrpcWebService<Routes>>: tonic::codegen::Service<request::Request<toni
c::transport::Body>>` is not satisfied
   --> src\launch\launch_server.rs:164:10
    |
164 |         .serve(address)
    |          ^^^^^ the trait `tonic::codegen::Service<request::Request<tonic::transport::Body>>` is not 
implemented for `Cors<GrpcWebService<Routes>>`
    |
    = help: the trait `tonic::codegen::Service<http::request::Request<ReqBody>>` is implemented for `Cors<
S>`
```

I look at #1320 several times, but the examples simply don't work with 11.0.

**Comment by boan-anbo** [comment]
I found the issue: tonic `11.0` doesn't work with `tower-http` `0.5.0` above. 

Downgrading `tower-http` to 0.4.4 allow cors works.

**Comment by Emulator000** [comment]
I think is same as this issue: https://github.com/hyperium/tonic/issues/1678
