### ISSUE TITLE
no method named `compile_well_known_types` found for struct `tonic_build::Builder` in the current scope

### ISSUE THREAD

**Issue by shantanoo-desai** [hyperium/tonic#581]
### Version

```
├── tonic v0.3.1
└── tonic-build v0.3.1
```

__Cargo.toml__

```toml

[dependencies]
tonic = "0.3"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
uuid = { version = "0.4", features = ["serde", "v4"] }

# Necessary when using Wellknown Types e.g. google/protobuf/wrappers.proto
prost-types = "0.7"

[build-dependencies]
tonic-build = "0.3"
```

### Platform

Windows Subsystem for Linux 2 on a Windows 10 64-bit machine

    5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Description

I am new at Rust, gRPC and Tonic totally and still learning. I am writing examples for the Book __gRPC: Up and Running__ in Rust using `tonic`.  There is a particular example in the book which uses `google/protobuf/wrappers.proto` in the proto file

__order_mgmt.proto__

```proto
syntax = "proto3";

import "google/protobuf/wrappers.proto";

package ordermgmt;

service OrderManagement {
    rpc getOrder(google.protobuf.StringValue) returns (Order);
}

message Order {
    string id = 1;
    repeated string items = 2;
    string description = 3;
    float price = 4;
    string destination = 5;
}

```

I have created the build file for each chapter and I am currently on  _Chapter 3: gRPC Communication Patterns_. I went through the code base and found out two examples:

1. [tests/wellknown-compiled/build.rs](https://github.com/hyperium/tonic/blob/61555ff2b5b76e4e3172717354aed1e6f31d6611/tests/wellknown-compiled/build.rs)
2. [test/wellknown/build.rs](https://github.com/hyperium/tonic/blob/61555ff2b5b76e4e3172717354aed1e6f31d6611/tests/wellknown/build.rs)

I am unable to figure out a proper documentation / example as to how such well-known types should be used, hence assuming I need to use `.compile_well_known_types(true)` in my build file.

__build.rs__

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {

    let chap2_iface_files = &["api/v1/protos/product_info.proto"];
    let dirs = &["."];

    // Chapter 2: Unary gRPC Pattern
    tonic_build::configure()
        .compile(chap2_iface_files, dirs)
        .unwrap();
    
    // Chapter 3: gRPC Communication Patterns
    let chap3_iface_files = &["api/v2/protos/order_mgmt.proto"];
    tonic_build::configure()
        .compile_well_known_types(true)
        .compile(chap3_iface_files, dirs)
        .unwrap();
    Ok(())
}
```

the above code causes the following Error:

```bash
$ cargo build
   Compiling gprc-rs v0.1.0 (/mnt/c/Users/des/Development/rust/projects/gprc-rs)
error[E0599]: no method named `compile_well_known_types` found for struct `tonic_build::Builder` in the current scope
  --> build.rs:14:10
   |
14 |         .compile_well_known_types(true)
   |          ^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `tonic_build::Builder`

error: aborting due to previous error

```

Is there something wrong that I am doing or the wrong version of `tonic`?

Can the developers please provide me some guidance as to how this error gets resolved?

Thanks

**Comment by davidpdrsn** [comment]
This is probably because the feature is merged but isn't deployed to crates.io yet. We're working on getting 0.4.1 out as we speak. Should happen within a day. Having some github+crates.io permission issues.

You can add tonic as a git dependency and it should work:

```toml
tonic = { git = "https://github.com/hyperium/tonic" }
```

**Comment by shantanoo-desai** [comment]
@davidpdrsn Thanks for the reply. I will close the issue once the v0.4.1 crate is available and have tested it, if you don't mind.

**Comment by davidpdrsn** [comment]
@shantanoo-desai tonic and tonic-build 0.4.1 is on crates.io 🚀

**Comment by shantanoo-desai** [comment]
@davidpdrsn Umm there seems to be a problem for me once I updated `tonic` from `0.3` to `0.4.1`

## Summary

`prost` is not being recognized when running `cargo build` for the `build.rs` with or without the `.compile_well_known_types(true)` in the file.

I am not sure if I doing something wrong here. The errors are really a lot so below you will find just the initial ones.

### Errors

```bash
 failed to resolve: could not find `alloc` in `prost`
 --> /mnt/c/Users/des/Development/rust/projects/gprc-rs/target/debug/build/gprc-rs-797c19cee6b0b8e9/out/ecommerce.rs:4:22
  |
4 |     pub id: ::prost::alloc::string::String,
  |                      ^^^^^ could not find `alloc` in `prost`

error[E0433]: failed to resolve: could not find `alloc` in `prost`
 --> /mnt/c/Users/des/Development/rust/projects/gprc-rs/target/debug/build/gprc-rs-797c19cee6b0b8e9/out/ordermgmt.rs:4:22
  |
4 |     pub id: ::prost::alloc::string::String,
  |                      ^^^^^ could not find `alloc` in `prost`

######## Removed brevity

 the trait bound `ecommerce::Product: prost::message::Message` is not satisfied
   --> /mnt/c/Users/des/Development/rust/projects/gprc-rs/target/debug/build/gprc-rs-797c19cee6b0b8e9/out/ecommerce.rs:195:40
    |
195 |                         let res = grpc.unary(method, req).await;
    |                                        ^^^^^ the trait `prost::message::Message` is not implemented for `ecommerce::Product`
    |
    = note: required because of the requirements on the impl of `tonic::codec::Codec` for `tonic::codec::ProstCodec<ecommerce::Product, ecommerce::ProductId>`
````

### Version

```bash
├── tonic v0.4.1
└── tonic-build v0.4.1
```

### `Cargo.toml`

```toml
[dependencies]
tonic = "0.4.1"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
uuid = { version = "0.4", features = ["serde", "v4"] }

# Necessary when using Wellknown Types e.g. google/protobuf/wrappers.proto
prost-types = "0.7"

[build-dependencies]
tonic-build = "0.4.1"
```

**Comment by davidpdrsn** [comment]
Tonic 0.4 requires prost 0.7. Does updating prost work for you?

**Comment by shantanoo-desai** [comment]
@davidpdrsn Thanks for the head's up!

I realized the blog post is old and my `Cargo.toml` has a lot of incompatible dependencies.

The Issue is resolved thanks to a bump in the following dependencies:

```
[dependencies]
tonic = "0.4.1"
prost = "0.7"
tokio = { version = "1.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
uuid = { version = "0.4", features = ["serde", "v4"] }

# Necessary when using Wellknown Types e.g. google/protobuf/wrappers.proto
prost-types = "0.7"

[build-dependencies]
tonic-build = "0.4.1"
```

based on the `examples` directory. It works for me and I didn't need to use `.compile_well_known_types(true)` in my `build.rs` file.


As a reference the repository is [shantanoo-desai/grpc-rust-tonic](https://github.com/shantanoo-desai/grpc-rust-tonic)
