### ISSUE TITLE
After upgrading from 0.8 to 0.9: Cannot find `TryInto` in this scope

### ISSUE THREAD

**Issue by gitmalong** [hyperium/tonic#1345]
Versions before upgrade:
```
tonic = "0.8.3"
tonic-build = "0.8.4"
```
Versions after upgrade:
```
tonic = "0.9.1"
tonic-build = "0.9.1"
```

```rust
//! build.rs
fn main() {
    tonic_build::configure()
        .build_server(false)
        .protoc_arg("--experimental_allow_proto3_optional")
        .compile(
            &["interface.proto", "storage.proto"],
            &["proto"],
        )
        .unwrap_or_else(|e| panic!("Failed to compile protos {:?}", e));
}
```

Error
```rust
cannot find trait `TryInto` in this scope
'enumflags2::_internal::core::convert::TryInto' is included in the prelude starting in Edition 2021
'std::convert::TryInto' is included in the prelude starting in Edition 2021
'core::convert::TryInto' is included in the prelude starting in Edition 2021
```

for generated client code
```rust

/// Generated client implementations.
pub mod interface_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct InterfaceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl InterfaceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>, // <-- cannot find trait `TryInto` in this scope
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
```

**Comment by LucioFranco** [comment]
Tonic 0.9 supports edition 2021 so you must upgrade your compiler and project to that. 

For more info on what the edition is you can read this https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html
