### ISSUE TITLE
Investigate build failure on Rust 1.51

### ISSUE THREAD

**Issue by davidpdrsn** [hyperium/tonic#666]
Running the tests with Rust 1.51 (the previous version) fails:

```
error[E0391]: cycle detected when computing the bounds for type parameter `T`
  --> /Users/davidpdrsn/dev/major/tonic/target/debug/build/integration-tests-27409cb8faefef33/out/test.rs:39:43
   |
39 |                 Response = http::Response<T::ResponseBody>,
   |                                           ^^^^^^^^^^^^^^^
   |
   = note: ...which again requires computing the bounds for type parameter `T`, completing the cycle
note: cycle used when computing explicit predicates of `pb::test_client::<impl at /Users/davidpdrsn/dev/major/tonic/target/debug/build/integration-tests-27409cb8faefef33/out/test.rs:23:5: 60:6>::with_interceptor`
  --> /Users/davidpdrsn/dev/major/tonic/target/debug/build/integration-tests-27409cb8faefef33/out/test.rs:39:43
   |
39 |                 Response = http::Response<T::ResponseBody>,
   |                                           ^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0391`.
error: could not compile `integration-tests`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0391]: cycle detected when computing the bounds for type parameter `T`
  --> /Users/davidpdrsn/dev/major/tonic/target/debug/build/tonic-health-c91ce4ef1f81caa8/out/grpc.health.v1.rs:23:1329
   |
23 | ...onic :: body :: BoxBody > , Response = http :: Response < T :: ResponseBody >> , < T as Service < http :: Request < tonic :: body :: B...
   |                                                              ^^^^^^^^^^^^^^^^^
   |
   = note: ...which again requires computing the bounds for type parameter `T`, completing the cycle
note: cycle used when computing explicit predicates of `proto::health_client::<impl at /Users/davidpdrsn/dev/major/tonic/target/debug/build/tonic-health-c91ce4ef1f81caa8/out/grpc.health.v1.rs:23:671: 23:3856>::with_interceptor`
  --> /Users/davidpdrsn/dev/major/tonic/target/debug/build/tonic-health-c91ce4ef1f81caa8/out/grpc.health.v1.rs:23:1329
   |
23 | ...onic :: body :: BoxBody > , Response = http :: Response < T :: ResponseBody >> , < T as Service < http :: Request < tonic :: body :: B...
   |                                                              ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0391`.
error[E0391]: cycle detected when computing the bounds for type parameter `T`
   --> /Users/davidpdrsn/dev/major/tonic/target/debug/build/tonic-reflection-ab51b8159f41b5ec/out/grpc.reflection.v1alpha.rs:185:43
    |
185 |                 Response = http::Response<T::ResponseBody>,
    |                                           ^^^^^^^^^^^^^^^
    |
    = note: ...which again requires computing the bounds for type parameter `T`, completing the cycle
note: cycle used when computing explicit predicates of `proto::server_reflection_client::<impl at /Users/davidpdrsn/dev/major/tonic/target/debug/build/tonic-reflection-ab51b8159f41b5ec/out/grpc.reflection.v1alpha.rs:166:5: 215:6>::with_interceptor`
   --> /Users/davidpdrsn/dev/major/tonic/target/debug/build/tonic-reflection-ab51b8159f41b5ec/out/grpc.reflection.v1alpha.rs:185:43
    |
185 |                 Response = http::Response<T::ResponseBody>,
    |                                           ^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0391`.
error[E0391]: cycle detected when computing the bounds for type parameter `T`
   --> /Users/davidpdrsn/dev/major/tonic/target/debug/build/interop-aab1922b6c306c4c/out/grpc.testing.rs:215:43
    |
215 |                 Response = http::Response<T::ResponseBody>,
    |                                           ^^^^^^^^^^^^^^^
    |
    = note: ...which again requires computing the bounds for type parameter `T`, completing the cycle
note: cycle used when computing explicit predicates of `pb::test_service_client::<impl at /Users/davidpdrsn/dev/major/tonic/target/debug/build/interop-aab1922b6c306c4c/out/grpc.testing.rs:196:5: 378:6>::with_interceptor`
   --> /Users/davidpdrsn/dev/major/tonic/target/debug/build/interop-aab1922b6c306c4c/out/grpc.testing.rs:215:43
    |
215 |                 Response = http::Response<T::ResponseBody>,
    |                                           ^^^^^^^^^^^^^^^

error: aborting due to previous error
```

Interestingly things work fine on 1.52.

We should ideally fix this, or make it clear that Rust 1.52 is required.

**Comment by davidpdrsn** [comment]
I've filed a rustc bug https://github.com/rust-lang/rust/issues/85659.
