### ISSUE TITLE
Build break on v0.4.0

### ISSUE THREAD

**Issue by bmmcq** [hyperium/tonic#550]
### Version
v0.4.0

### Platform
macos( Darwin Kernel Version 19.5.0)

### Crates
examples

### Description
run `cargo build --bin helloworld-server ` will fail on v0.4.0, with error messages : 
```
error[E0658]: procedural macros cannot be expanded to statements
  --> tonic/src/codec/encode.rs:47:5
   |
47 | /     async_stream::stream! {
48 | |         let mut buf = BytesMut::with_capacity(BUFFER_SIZE);
49 | |         futures_util::pin_mut!(source);
50 | |
...  |
74 | |         }
75 | |     }
   | |_____^
```
but on v0.3.1 it is ok;

**Comment by hhanh00** [comment]
Same thing on linux. Using nightly rust works.

**Comment by davidpdrsn** [comment]
I cannot reproduce this:

```
❯ cargo build --bin helloworld-server
   Compiling tonic v0.4.0 (/Users/david.pedersen/dev/major/tonic/tonic)
   Compiling tonic-health v0.3.0 (/Users/david.pedersen/dev/major/tonic/tonic-health)
   Compiling examples v0.1.0 (/Users/david.pedersen/dev/major/tonic/examples)
    Finished dev [unoptimized + debuginfo] target(s) in 9.55s
```

I'm on macOS 10.15.7.

**Comment by bmmcq** [comment]
After updating the "rustc" version to 1.50, there are no problems with the building. It seems that the "rust 1.45" or other old versions  may have problems;
